// Mocks generated by Mockito 5.4.5 from annotations
// in dojo_flutter/test/get_movie_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dojo_flutter/feature/api_client/data/datasource/data_source.dart'
    as _i2;
import 'package:dojo_flutter/feature/api_client/data/repository/api_movie_repository.dart'
    as _i4;
import 'package:dojo_flutter/feature/api_client/domain/entity/movie.dart'
    as _i6;
import 'package:dojo_flutter/feature/local_database/data/datasource/database_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataSource_0 extends _i1.SmartFake implements _i2.DataSource {
  _FakeDataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseDataSource_1 extends _i1.SmartFake
    implements _i3.DatabaseDataSource {
  _FakeDatabaseDataSource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiMovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiMovieRepository extends _i1.Mock
    implements _i4.ApiMovieRepository {
  @override
  _i2.DataSource get mainDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#mainDataSource),
            returnValue: _FakeDataSource_0(
              this,
              Invocation.getter(#mainDataSource),
            ),
            returnValueForMissingStub: _FakeDataSource_0(
              this,
              Invocation.getter(#mainDataSource),
            ),
          )
          as _i2.DataSource);

  @override
  _i3.DatabaseDataSource get localDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#localDatabase),
            returnValue: _FakeDatabaseDataSource_1(
              this,
              Invocation.getter(#localDatabase),
            ),
            returnValueForMissingStub: _FakeDatabaseDataSource_1(
              this,
              Invocation.getter(#localDatabase),
            ),
          )
          as _i3.DatabaseDataSource);

  @override
  _i5.Future<List<_i6.Movie>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i5.Future<List<_i6.Movie>>.value(<_i6.Movie>[]),
            returnValueForMissingStub: _i5.Future<List<_i6.Movie>>.value(
              <_i6.Movie>[],
            ),
          )
          as _i5.Future<List<_i6.Movie>>);
}
