// Mocks generated by Mockito 5.4.5 from annotations
// in dojo_flutter/test/sql_database_proxy_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dojo_flutter/feature/api_client/domain/entity/movie.dart'
    as _i5;
import 'package:dojo_flutter/feature/local_database/data/datasource/sqlite_database_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [SqlDatabaseDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSqlDatabaseDataSource extends _i1.Mock
    implements _i3.SqlDatabaseDataSource {
  @override
  _i2.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_0(this, Invocation.getter(#db)),
        returnValueForMissingStub: _FakeDatabase_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.Database);

  @override
  set db(_i2.Database? _db) => super.noSuchMethod(
        Invocation.setter(#db, _db),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> insertMovies(List<_i5.Movie>? movies) => (super.noSuchMethod(
        Invocation.method(#insertMovies, [movies]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(#getPopularMovies, []),
        returnValue: _i4.Future<Map<String, dynamic>>.value(
          <String, dynamic>{},
        ),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
          <String, dynamic>{},
        ),
      ) as _i4.Future<Map<String, dynamic>>);
}
