// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUnv9H06VMZ5KMn2OUZQtMrPKccrZ8eq4',
    appId: '1:304748079408:web:238decc8285cbeeb1580f5',
    messagingSenderId: '304748079408',
    projectId: 'dojo-abril-2025',
    authDomain: 'dojo-abril-2025.firebaseapp.com',
    storageBucket: 'dojo-abril-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsDsgXvTkmlaX5OdCnhx8vs15TrvtpDDY',
    appId: '1:304748079408:android:6f8e2432405216631580f5',
    messagingSenderId: '304748079408',
    projectId: 'dojo-abril-2025',
    storageBucket: 'dojo-abril-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ZAmMvERCPfynPPMjF7eykUBvlLQHRjI',
    appId: '1:304748079408:ios:d77c7ab8e42bec091580f5',
    messagingSenderId: '304748079408',
    projectId: 'dojo-abril-2025',
    storageBucket: 'dojo-abril-2025.firebasestorage.app',
    iosBundleId: 'com.example.dojoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ZAmMvERCPfynPPMjF7eykUBvlLQHRjI',
    appId: '1:304748079408:ios:d77c7ab8e42bec091580f5',
    messagingSenderId: '304748079408',
    projectId: 'dojo-abril-2025',
    storageBucket: 'dojo-abril-2025.firebasestorage.app',
    iosBundleId: 'com.example.dojoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUnv9H06VMZ5KMn2OUZQtMrPKccrZ8eq4',
    appId: '1:304748079408:web:c20d873e6cb5bfcd1580f5',
    messagingSenderId: '304748079408',
    projectId: 'dojo-abril-2025',
    authDomain: 'dojo-abril-2025.firebaseapp.com',
    storageBucket: 'dojo-abril-2025.firebasestorage.app',
  );
}
